### ISSUE TITLE
space between panels, console error

### ISSUE THREAD

**Issue by jshbll** [guidobouman/panelsnap#140]
Regardless of what I do I get the console error 'PanelSnap does not support space between panels, snapping back.'

this is also an error on http://panelsnap.com

**Comment by guidobouman** [comment]
On what browser are you experiencing this? I don't see this happening on panelsnap.com on my browsers. (Chrome, Safari & Firefox all on macOS)

**Comment by jshbll** [comment]
Chrome, on mac os x

**Comment by guidobouman** [comment]
And you see the error `PanelSnap does not support space between panels, snapping back.` on https://panelsnap.com in Chrome on macOS?

**Comment by guidobouman** [comment]
What version of Chrome? (go to chrome://settings/help)

**Comment by rhettparkinson** [comment]
Seeing this on 'panelsnap.com'

# What version of Chrome are you using?
Version 71.0.3578.98

**Comment by guidobouman** [comment]
@rhettparkinson Do you maybe use a mouse instead of a trackpad?

**Comment by jappe999** [comment]
I also see this error on Firefox 67.0b2 and Chrome 73.0.3683.75 on Ubuntu.

**Comment by jappe999** [comment]
To answer your questions:

- What version of Chrome are you using?
  Version 73.0.3683.75

- Can you explain when this is happening?
  This is happening every time I scroll or click in the container.

- What device(s) are you using to scroll?
  The error appears when I use a mouse, trackpad and the native scrollbar.

- Are you scrolling with the device or do you drag the scrollbar UI?
  Both. And both give the error.

**Comment by guidobouman** [comment]
Are you using Windows , macOS or Linux?

**Comment by ezracelli** [comment]
Any word on this? Getting the same console error with 100vh panels in Chrome 74.0.3729.169 (on MacOS 10.14.5). Functionality is fine, just complains in the console.

**Comment by guidobouman** [comment]
Just followed a hunch and found the bug: I normally do not use a mouse. It's when a mouse is attached to a MacBook that a scrollbar is placed within each overflowing container. Much like how Windows always renders a scrollbar. I did test a with mouse, but did not check for console errors, apparently.

This bug is annoying, but not harmful. It triggers after snapping, and the whole plugin seems to work as expected otherwise.

Please correct me if you think I'm wrong.

Expect a fix this week.

**Comment by ezracelli** [comment]
@guidobouman I looked around a bit and for me it looks like the issue was I wasn't using `100vh`/`100vw` panels but still using the body as the scrolling container. That means that after snapping (like you said), `elementFillsContainer` in `utilities.js` was returning false.

```javascript
export function elementFillsContainer(container, element) {
  const containerRect = getContainerRect(container);
  const elementRect = element.getBoundingClientRect();

  return (
    elementRect.top <= containerRect.top &&
    elementRect.bottom >= containerRect.bottom &&
    elementRect.left <= containerRect.left &&
    elementRect.right >= containerRect.right
  );
}
```

It would be great to be able to detect vertical/horizontal scrolling and only check those constraints vs checking all 4, but this seems more like additional functionality rather than a bug fix 😁

**Comment by guidobouman** [comment]
I should calculate the scrollbar size, and remove those from the equation.

Proof of concept: https://codepen.io/guidobouman/pen/PrNLag

**Comment by guidobouman** [comment]
Code fix implemented. Works in browsers, but breaks tests. Working on it.
